POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNpY2Vyb1VzZXIiLCJpZCI6IjYzZjc2YTllYzI0MjM0Mzg3ODhjZjI2NiIsImlhdCI6MTY3NzM2NjU4MX0.e3NgbsUpXFoBAcErXICBToR2PYunWT-CEvZFiYkOvzo

{
    "title": "Tacituksen blogi 2 (Ciceron kommentaari)",
    "author": "Tacitus",
    "url": "http://tacitusUrl",
    "likes": 2001
}